import { Client } from '../_classes/client';

export let Clients: Client[] = [
  {
    id: 11,
    snils: '12345678901',
    fam: null,
    im: 'Ваня',
    ot: 'Сидорович',
    birthday: null,
    street_id: null,
    dom: null,
    korp: null,
    kv: null,
    checked: true,
    user_id: 1,
    dt: null
  },
  {
    id: 12,
    snils: '10234567890',
    fam: null,
    im: 'Даша',
    ot: 'Сидорович',
    birthday: null,
    street_id: null,
    dom: null,
    korp: null,
    kv: null,
    checked: true,
    user_id: 1,
    dt: null
  },
  {
    id: 13,
    snils: '10334567890',
    fam: null,
    im: 'Митя',
    ot: 'Петрович',
    birthday: null,
    street_id: null,
    dom: null,
    korp: null,
    kv: null,
    checked: true,
    user_id: 1,
    dt: null
  },
  {
    id: 14,
    snils: '10234557890',
    fam: null,
    im: 'Эдик',
    ot: 'Васевич',
    birthday: null,
    street_id: null,
    dom: null,
    korp: null,
    kv: null,
    checked: true,
    user_id: 1,
    dt: null
  },
  {
    id: 15,
    snils: '90234567890',
    fam: null,
    im: 'Яночка',
    ot: 'Викторовна',
    birthday: null,
    street_id: null,
    dom: null,
    korp: null,
    kv: null,
    checked: true,
    user_id: 2,
    dt: null
  },
];