import { Transportation } from '../_classes/list/transportation';

export let Transportations: Transportation[] = [
  {
    id: 1,
    client_id: 11,
    car_id: 3,
    car: 'а412ао74',
    punkt_id: 1,
    punkt: 'Органы государственной власти и органы местного самоуправления',
    a_street_id: 23,
    a_street: 'Комсомольский пр-кт',
    a_dom: 2,
    a_korp: null,
    a_adr: 'Победы, пр-кт, 2',
    a_dt: Date.parse('12.31.2017 12:00'),
    b_street_id: 89,
    b_street: 'Комсомольский пр-кт',
    b_dom: 78,
    b_korp: null,
    b_adr: 'Комсомольский, пр-кт, 78',
    b_dt: Date.parse('12.31.2017 13:00'),
    checked: false,
    comments: null,
    status: true,
    user_id: 11,
    user: 'А.А. Чехов',
    dt: Date.parse('12.31.2017 13:00')
  },
  {
    id: 1,
    client_id: 11,
    car_id: 4,
    car: 'у435ка174',
    punkt_id: 1,
    punkt: 'Органы государственной власти и органы местного самоуправления',
    a_street_id: 23,
    a_street: 'Победы пр-кт',
    a_dom: 2,
    a_korp: null,
    a_adr: 'Победы, пр-кт, 2',
    a_dt: Date.parse('14.31.2017 10:00'),
    b_street_id: 89,
    b_street: 'Комсомольский пр-кт',
    b_dom: 78,
    b_korp: null,
    b_adr: 'Комсомольский, пр-кт, 78',
    b_dt: Date.parse('14.31.2017 11:00'),
    checked: false,
    comments: null,
    status: true,
    user_id: 11,
    user: 'А.А. Сехов',
    dt: Date.parse('13.31.2017 13:00')
  }
];